### ISSUE TITLE
New system log appears to be broken

### ISSUE THREAD

**Issue by amcgee** [WellDone/MoMo-Firmware#164]
Running `momo controller read_log` throws the following error:

```
ValidationError: Buffer must be of length sizeof(GenericLogEntry) = 16 bytes
Additional Information:
buffer: 3=?(
```

Running clear_log and then read_log accesses the SystemLog momo context but running `momo controller read_log help` fails like so:

```
(SystemLog) help

SystemLog
A list of log entries from the MoMo system log

The MoMo controller keeps an ordered list of timestamped
logged events, which can contain arbitrary parameters. 
This class encapsulates one such list and allows you to
access, filter and display the log entries.

Defined Functions:
Traceback (most recent call last):
  File "/usr/local/bin/momo", line 9, in <module>
    load_entry_point('pymomo==1.0.4', 'console_scripts', 'momo')()
  File "/usr/local/lib/python2.7/dist-packages/pymomo/scripts/momo.py", line 88, in main
    line, finished = shell.invoke(line)
  File "/usr/local/lib/python2.7/dist-packages/pymomo/utilities/typedargs/shell.py", line 267, in invoke
    return _do_help(context, line)
  File "/usr/local/lib/python2.7/dist-packages/pymomo/utilities/typedargs/shell.py", line 108, in _do_help
    print_dir(context)
  File "/usr/local/lib/python2.7/dist-packages/pymomo/utilities/typedargs/shell.py", line 84, in print_dir
    print " - " + annotate.get_signature(fun)
  File "/usr/local/lib/python2.7/dist-packages/pymomo/utilities/typedargs/annotate.py", line 128, in get_signature
    name = f.__name__
AttributeError: LogDefinitionMap instance has no attribute '__name__'
```

Finally, running `momo controller reset` and then `momo controller read_log` again results in the original ValidationError.

This is running controller firmware v4.1 from the latest dev branch on the newest hardware version.

**Comment by amcgee** [comment]
This has been resolved.
